# Generated by Django 5.1.1 on 2024-10-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.AddField(
            model_name='service',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
