# Generated by Django 5.1.1 on 2024-10-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_service_image_service_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='subservice1_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='subservice1_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='subservice2_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='subservice2_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
