# Generated by Django 5.1.1 on 2024-10-30 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_client_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.client'),
        ),
    ]
