# Generated by Django 5.1.1 on 2024-10-30 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_service_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='client',
            new_name='user',
        ),
    ]
