# Generated by Django 5.1.1 on 2024-10-30 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_rename_client_service_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='user',
            new_name='client',
        ),
    ]
