# Generated by Django 5.1.1 on 2024-10-30 14:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_rename_user_service_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='date_service',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
